# Generated by Django 4.0.1 on 2022-02-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='direction',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='usuario',
        ),
    ]
