# Generated by Django 4.0.1 on 2022-02-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_direction_client_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='direccion',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telefono',
            new_name='phone',
        ),
    ]
